[tool.black]
line-length = 120
target-version = ['py38']

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "duplicate-code",
    "too-few-public-methods",
    "too-many-return-statements",
    "no-else-return",
    "global-statement",
    "unused-argument",
    "import-outside-toplevel",
    "broad-exception-caught",
    "consider-using-with",
    "subprocess-run-check",
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "inconsistent-return-statements",
    "too-many-locals",
    "too-many-branches",
    "too-many-statements"
]
